//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.15 at 03:48:44 PM IRKT 
//


package ru.ttv.meteringvaluesregistrationservice.soap.metering;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.ttv.meteringvaluesregistrationservice.soap.metering package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.ttv.meteringvaluesregistrationservice.soap.metering
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ImportMeteringValuesRequest }
     * 
     */
    public ImportMeteringValuesRequest createImportMeteringValuesRequest() {
        return new ImportMeteringValuesRequest();
    }

    /**
     * Create an instance of {@link ImportMeteringValuesResponse }
     * 
     */
    public ImportMeteringValuesResponse createImportMeteringValuesResponse() {
        return new ImportMeteringValuesResponse();
    }

    /**
     * Create an instance of {@link MeteringRegistrationResponseData }
     * 
     */
    public MeteringRegistrationResponseData createMeteringRegistrationResponseData() {
        return new MeteringRegistrationResponseData();
    }

}
