//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.15 at 03:48:44 PM IRKT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://meteringvaluesregistrationservice.ttv.ru/soap/metering", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.ttv.meteringvaluesregistrationservice.soap.metering;
